### ISSUE TITLE
Elevator Timing

### ISSUE THREAD

**Issue by josh-degraw** [josh-degraw/ElevatorSimulator#3]

**Comment by josh-degraw** [comment]
@maxraustin @nickarnett
So currently, the formula we've got is:
```csharp
int delay()
{
    const int ACCEL_DELAY = 4;
    const int DECEL_DELAY = 2 * ACCEL_DELAY;

    var floorTravel = Math.Abs(destFloor - currFloor);
    var x = ACCEL_DELAY + DECEL_DELAY * floorTravel + ((floorTravel * floorHeight)/(elevatorSpeed / 60));
    return x;
}
```
Do I have that right as far as the texts?

**Comment by maxraustin** [comment]
Yes, this looks correct to me. You should get decent delay timings with that. For the door opening delay, we can use the timings that others have found (~5 seconds)

**Comment by josh-degraw** [comment]
Okay cool. Do we have any timings for the doors opening and closing?

**Comment by maxraustin** [comment]
Not yet. For my tests I was just using the timings in the sample file.

**Comment by josh-degraw** [comment]
Do we have / need any sort of timing for people entering and exiting the Elevators?

**Comment by nickarnett** [comment]
I'll work on some of this. I'll do some final testing and go over any last bits from the sample file online.
