### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by josh-degraw** [josh-degraw/ElevatorSimulator#6]
How do we want to change the settings? 

- Do we want to remove any of the settings we have in there now?
- How important is it to move the settings away from the Ribbon view?

**Comment by maxraustin** [comment]
So I've been trying some different ideas out for this,  and I can't really think of a better way than just having them at the top. My thought is that having the information displayed to the user is easier to understand than having an expandable one. IE, if you wanted to see the effect that changing a value has on your system, its more of a pain to have to open the flyout just to see what you had it set to every time. I did try a few different layouts but they felt just "different" not really objectively better or worse

**Comment by josh-degraw** [comment]
I think another good way to do this would be to just do kinda what Prof was saying in class and have the user select a model on startup and hide them away afterwords, and just allow to switch between them, maybe showing the settings at that point but not having them be changeable.

**Comment by nickarnett** [comment]
Agreed, if we have each model come with a bunch of preset data that he doesn't have to modify that could make things easier. I think we still need to display that information but not make it changeable by the user. 

One thing to think about, when we make the option of having another elevator, do we automatically select the same elevator as the first (I think this is the most natural, you wouldn't buy two different kinds and stick them together), or do we give him the option to choose each one individually?
