### ISSUE TITLE
Adding Passengers

### ISSUE THREAD

**Issue by josh-degraw** [josh-degraw/ElevatorSimulator#7]
I'm getting close on this one.

**Comment by josh-degraw** [comment]
Okay. When the elevator is at a floor, it adds the passengers on that floor, and when it arrives at a floor, it picks up the passengers on that floor. The one thing still not working is just sending the elevator to a floor when a button is pressed, if the elevator is not moving.

**Comment by nickarnett** [comment]
The other day when the professor was looking at the project he didn't really know what the floor button- add passenger section was for and how to use it. What if we switched it to something like this. I know we've talked about doing something like this before not sure if we ever got to it.

This would probably clean up a bit of the UI and make it more understandable and intuitive. 

![add passender](https://user-images.githubusercontent.com/17135396/37464771-fdb079b6-281e-11e8-9c30-9d2041c8a303.PNG)

**Comment by nickarnett** [comment]
Another side note, he sounds like he really wants there to be different types of passengers. Disabled, Normal, and Freight. I'll try and get some timings for these (If there are any) and we can just plan to have disabled and freight as taking up the space of 2 or more people. It does mean that when we add a passenger we will also need a way to not only select a destination floor but also the passenger type. Maybe underneath the floor selection there could also be the option or checkbox for disabled or freight (assuming the normal addition will be a regular passenger?

**Comment by nickarnett** [comment]
These are just mock ups but might give us a starting point
![add passender](https://user-images.githubusercontent.com/17135396/37482920-09daa262-284b-11e8-9a00-511f0b0a402d.PNG)

**Comment by josh-degraw** [comment]
I got the vibe that it was just that there was a group doing the passenger type thing, not that it was required... I'd think for now just having one that works like it should would be sufficient
