### ISSUE TITLE
Event Statistics

### ISSUE THREAD

**Issue by josh-degraw** [josh-degraw/ElevatorSimulator#9]
We should have a decent way to view aggregated statistics for events. Possible Ideas include:

- As-needed querying
    - i.e. query the `Logger.Events` object to get the events, then calculate the values as needed
- Creating a `Stats` class that could listen for events and hold statistical info
- Change event log system to use enums as event types, to make aggregation simpler
    - Downside: way less pluggable

**Comment by maxraustin** [comment]
I think I could probably do this one too. Making a Stats class that holds information about passenger timings doesn't sound too bad. Would this type of implementation work?
1. Stats class has a collection of "Instant" for passenger wait times
2. When a passenger gets off an elevator Stats will get this information from them
3. Then Stats will have a FCN that calculates information about it like averages, and returns it

Does this seem good? We can check average elevator movement times, etc with this.

**Comment by josh-degraw** [comment]
That's a good initial approach for sure. I say we start there for this milestone (or honestly if it's just passengers we could have it as a static property or something).

I'll say also that depending on what we'll want to be reporting, we could extend this and have it be for any kind of statistic. 

One thing I was thinking of is that the `Stats` class could hold a single scalar value, i.e. `AvgPassengerWait` that could be updated via the `Logger.OnItemLogged` event.

**Comment by josh-degraw** [comment]
Actually it'd probably make more sense to add events to the `Passenger` class that fire when they change states. You could already do it with `PropertyChanged` but it'll be more intuitive with standalone events. I can add those in.

**Comment by maxraustin** [comment]
Okay. Right now I have stats as a singleton which has a collection of duration. Seemed to be the easiest way to aggregate times

**Comment by maxraustin** [comment]
So I've pushed up what I have done so far for this thing. It's very late at night right now lol. But you should be able to see what i had in mind at least. It's nothing that great or fancy and probably should be changed up, but its a start. Right now it's given and stores only information about how long a passenger waits for (time waiting plus time in elevator). Then it has a fcn to get the average.

**Comment by nickarnett** [comment]
It might be good to also track a high and low value. The average is what we're really looking for to determine the best elevator but knowing the stat for the longest wait and total time as well as the shortest wait and total time would also be valuable and not that hard to track.

**Comment by josh-degraw** [comment]
Hey guys, check out the `Statistic` classes (specifically `DurationStatistic`) I put in there. I was poking around in your code @maxraustin and I thought of a way to build on it. I was just messing with this concept and I think it could come in handy. Currently it's set up to keep the `Min`, `Max`, and `Average`, and it's updated as items are added, so it should always be up-to-date. I haven't actually tried it out yet, but if one of you guys want to test using them that would be shweet.

**Comment by maxraustin** [comment]
Yeah ill take a look at it later tonight once I finish this other assignment I'm doing
